apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-mgmt-backend
  namespace: user-mgmt
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /users/$2
spec:
  ingressClassName: nginx
  rules:
    - host: user-mgmt-k8s-nt.duckdns.org
      http:
        paths:
          - path: /api/users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-mgmt-frontend
  namespace: user-mgmt
spec:
  ingressClassName: nginx
  rules:
    - host: user-mgmt-k8s-nt.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
